### ISSUE TITLE
parsing vlc headers worked with libbindgen, fails with recently merged bindgen

### ISSUE THREAD

**Issue by Geal** [servo/rust-bindgen#481]
Hello,

I used libbindgen a lot during my work on adding some Rust code inside VLC media player, and the recent changes broke header parsing. I extracted a test project to reproduce the issue here: https://github.com/Geal/bindgen-vlc-test

Istead of generating the `src/stream.rs` file with a few definitions (cf https://github.com/Geal/bindgen-vlc-test/blob/master/build.rs ), it generates the following logs:

Output:

```
error: failed to run custom build command for `bindgen-vlc-test v0.1.0 (file:///Users/geal/dev/videolan/bindgen-vlc-test)`
process didn't exit successfully: `/Users/geal/dev/videolan/bindgen-vlc-test/target/debug/build/bindgen-vlc-test-b23f79ec58e723dd/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=.
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:101:31: error: unknown type name 'block_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:105:5: error: must use 'struct' tag to refer to type 'block_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:107:5: error: unknown type name 'uint8_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:109:5: error: unknown type name 'uint8_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:112:5: error: unknown type name 'uint32_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:115:5: error: unknown type name 'mtime_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:116:5: error: unknown type name 'mtime_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:117:5: error: unknown type name 'mtime_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:139:1: error: unknown type name 'VLC_API', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:139:9: error: expected identifier or '(', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:1: error: unknown type name 'VLC_API', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:16: error: expected ';' after top level declarator, err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:141:1: error: must use 'struct' tag to refer to type 'block_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:141:27: error: must use 'struct' tag to refer to type 'block_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:141:64: error: expected function body after function declarator, err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:142:1: error: unknown type name 'VLC_API', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:142:16: error: expected ';' after top level declarator, err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:144:42: error: must use 'struct' tag to refer to type 'block_t', err: true
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:144:56: error: must use 'struct' tag to refer to type 'block_t', err: true
fatal error: too many errors emitted, stopping now [-ferror-limit=], err: true

--- stderr
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:101:31: error: unknown type name 'block_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:105:5: error: must use 'struct' tag to refer to type 'block_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:107:5: error: unknown type name 'uint8_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:109:5: error: unknown type name 'uint8_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:112:5: error: unknown type name 'uint32_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:115:5: error: unknown type name 'mtime_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:116:5: error: unknown type name 'mtime_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:117:5: error: unknown type name 'mtime_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:139:1: error: unknown type name 'VLC_API'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:139:9: error: expected identifier or '('
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:1: error: unknown type name 'VLC_API'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:16: error: expected ';' after top level declarator
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:141:1: error: must use 'struct' tag to refer to type 'block_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:9: note: struct 'block_t' is hidden by a non-type declaration of 'block_t' here
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:141:27: error: must use 'struct' tag to refer to type 'block_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:9: note: struct 'block_t' is hidden by a non-type declaration of 'block_t' here
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:141:64: error: expected function body after function declarator
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:142:1: error: unknown type name 'VLC_API'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:142:16: error: expected ';' after top level declarator
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:144:42: error: must use 'struct' tag to refer to type 'block_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:9: note: struct 'block_t' is hidden by a non-type declaration of 'block_t' here
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:144:56: error: must use 'struct' tag to refer to type 'block_t'
/Users/geal/dev/videolan/bindgen-vlc-test/vlc_block.h:140:9: note: struct 'block_t' is hidden by a non-type declaration of 'block_t' here
fatal error: too many errors emitted, stopping now [-ferror-limit=]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /Users/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-mac/build/src/libcore/result.rs:870
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Is there something wrong with my approach? In the shortterm, I'd like to generate bindings for the complete VLC API.

**Comment by emilio** [comment]
Hmm.. So that's a clang error, do you happen to know under what version it worked? Seems like some header includes may be missing?

**Comment by Geal** [comment]
it worked with libbindgen 0.17.0. Commit: https://github.com/servo/rust-bindgen#8013e0c7bc28e0883363649c94360b4878d1d742

I don't think it's missing headers, it's apparently complaining about a missing block_t at https://github.com/Geal/bindgen-vlc-test/blob/master/include/vlc_block.h#L101 while it is defined just after in the same file: https://github.com/Geal/bindgen-vlc-test/blob/master/include/vlc_block.h#L103-L121

**Comment by emilio** [comment]
Well, I commented about the missing headers because of the "unknown type name uintxx_t. I'll try to take a look today, thanks for reporting it! :)

**Comment by emilio** [comment]
Hmm... From taking a quick look at that header, is it valid? I mean, in C you can't use a type before it's defined, so... Anyway, digging now.

**Comment by emilio** [comment]
I _believe_ it worked because it was including the system vlc_block.h? Otherwise I don't know where those macros come from (`VLC_API`, etc.). They're indeed not defined anywhere.

**Comment by emilio** [comment]
I'm assuming the whole thing is https://github.com/Geal/vlc_module.rs, I've been able to reproduce there.

**Comment by emilio** [comment]
I've been able to reproduce the error, but the build isn't working either with that bindgen revision.

Mainly, what happens is that `vlc_block.h`, etc don't include `vlc_common.h`, so when parsing those files standalone clang complains.

This patch makes the binding generation succeed:

```diff
diff --git a/Cargo.toml b/Cargo.toml
index 055e82d..f598fd7 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -12,7 +12,7 @@ default = ["link-vlc"]
 libc = "^0.2.0"
 
 [build-dependencies]
-bindgen = "^0.20"
+bindgen = "0.21"
 
 #[build-dependencies.libbindgen]
 #git = "https://github.com/servo/rust-bindgen"
diff --git a/build.rs b/build.rs
index 8f6b06c..cab2e6d 100644
--- a/build.rs
+++ b/build.rs
@@ -8,9 +8,11 @@ fn main() {
   println!("cargo:rustc-link-search=native=.");
   let include_arg = concat!("-I", env!("INCLUDE_DIR"));
 
+  const VLC_COMMON_PATH: &'static str = concat!(env!("INCLUDE_DIR"), "/vlc_common.h");
+
   let _ = bindgen::builder()
     .clang_arg(include_arg)
-    .header(concat!(env!("INCLUDE_DIR"), "/vlc_common.h"))
+    .header(VLC_COMMON_PATH)
     .whitelisted_type("vlc_fourcc_t")
     .whitelisted_type("mtime_t")
     .whitelisted_type("es_out_id_t")
@@ -21,6 +23,8 @@ fn main() {
 
   let _ = bindgen::builder()
     .clang_arg(include_arg)
+    .clang_arg("-include")
+    .clang_arg(VLC_COMMON_PATH)
     .header(concat!(env!("INCLUDE_DIR"), "/vlc_plugin.h"))
     .whitelisted_type("vlc_module_properties")
     .use_core()
@@ -44,6 +48,8 @@ fn main() {
 
   let _ = bindgen::builder()
     .clang_arg(include_arg)
+    .clang_arg("-include")
+    .clang_arg(VLC_COMMON_PATH)
     .header(concat!(env!("INCLUDE_DIR"), "/vlc_stream.h"))
     .whitelisted_type("stream_t")
     .whitelisted_function("stream_Read")
@@ -55,6 +61,8 @@ fn main() {
 
   let _ = bindgen::builder()
     .clang_arg(include_arg)
+    .clang_arg("-include")
+    .clang_arg(VLC_COMMON_PATH)
     .header(concat!(env!("INCLUDE_DIR"), "/vlc_demux.h"))
     .whitelisted_function("demux_New")
     .whitelisted_function("demux_vaControlHelper")
@@ -75,6 +83,8 @@ fn main() {
 
   let _ = bindgen::builder()
     .clang_arg(include_arg)
+    .clang_arg("-include")
+    .clang_arg(VLC_COMMON_PATH)
     .header(concat!(env!("INCLUDE_DIR"), "/vlc_es.h"))
     .whitelisted_function("es_format_Init")
     .whitelisted_type("es_format_category_e")
@@ -86,6 +96,8 @@ fn main() {
 
   let _ = bindgen::builder()
     .clang_arg(include_arg)
+    .clang_arg("-include")
+    .clang_arg(VLC_COMMON_PATH)
     .header(concat!(env!("INCLUDE_DIR"), "/vlc_es_out.h"))
     .whitelisted_type("es_out_query_e")
     .use_core()
```

**Comment by emilio** [comment]
After that patch, the rustc errors with some stuff that aren't bindgen's business I think:

```
error[E0432]: unresolved import `ffi::demux::vlc_object_t`
 --> src/ffi/definitions.rs:4:5
  |
4 | use ffi::demux::vlc_object_t;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^ no `vlc_object_t` in `ffi::demux`

error[E0432]: unresolved import `ffi::es_out_t`
 --> src/vlc.rs:7:31
  |
7 |                 vlc_fourcc_t, es_out_t, es_out_id_t, input_thread_t, module_t, libvlc_int_t};
  |                               ^^^^^^^^ no `es_out_t` in `ffi`. Did you mean to use `es_out`?

error[E0412]: cannot find type `__va_list_tag` in this scope
  --> src/ffi/demux.rs:14:45
   |
14 |                                  args: *mut __va_list_tag)
   |                                             ^^^^^^^^^^^^^ not found in this scope
   |
   = help: possible candidate is found in another module, you can import it into scope:
             `use ffi::stream::__va_list_tag;
```

**Comment by emilio** [comment]
Note that I built with my system VLC headers and a dummy VLC version, I don't know what version of the VLC API is that build script targeting. This is the command that I used:

```
INCLUDE_DIR=/usr/include/vlc/plugins VLC_VERSION=2240 cargo build
```

**Comment by Geal** [comment]
it seems the new bindgen is much less forgiving :)

I'm getting somewhere with your patch, now it's a matter of hiding the necessary types and use raw_line to import them from other generated modules. Or do you know a better solution?

**Comment by emilio** [comment]
Yeah, that's pretty much the way to go if you want to include the same header from multiple files and not getting duplicated definitions.

Thanks for confirming it works! I'm closing this for now, feel free to report any other issues you have, happy to help :)
